# Generated by Django 2.2 on 2019-06-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledir', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='This is default text given by purushottam for testing purpose.'),
        ),
    ]
