# Generated by Django 2.2 on 2019-06-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledir', '0004_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
