# Generated by Django 2.2 on 2019-06-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiledir', '0005_auto_20190626_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='my location default', max_length=120),
        ),
    ]
